# ðŸ”„ Automated Updates
version: 2
updates:
  # Check for Dockerfile updates (Base images like eclipse-temurin)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "experimental"
    labels:
      - "docker"
      - "dependencies"

  # Check for GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "experimental"
    labels:
      - "github-actions"
      - "dependencies"